project_id = "uusegezraxxagnktnypz"

[functions.google-drive-oauth-callback]
verify_jwt = false

[functions.search-google-drive]
verify_jwt = true

[functions.ai-search]
verify_jwt = true

[functions.multi-source-search]
verify_jwt = true

[functions.ai-summarize]
verify_jwt = true
